# Site wide configuration

title: Tony Phipps
locale: en_US
logo: logo.png

remote_theme: cotes2020/jekyll-theme-chirpy
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
- jekyll-remote-theme
 
